### ISSUE TITLE
スマホでレイアウトが崩れている

### ISSUE THREAD

**Issue by unarist** [scalamatsuri/2024.scalamatsuri.org#67]
iPhone12mini で https://scalamatsuri.org/ja を開いた時の様子です:

![image](https://github.com/scalamatsuri/2024.scalamatsuri.org/assets/705555/d72f64dd-a59a-49f0-b9d5-0410be318884)

**Comment by xuwei-k** [comment]
もっと横幅が狭い場合 😇 

![image](https://github.com/scalamatsuri/2024.scalamatsuri.org/assets/389787/4b3808cb-1ace-499d-984c-3413c6117d70)

**Comment by windymelt** [comment]
手元で様子を見ようとしたのですが

```
% node -v
v18.18.0
% yarn -v
1.22.21
% yarn install 
yarn install v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
[3/4] Linking dependencies...
warning "workspace-aggregator-64c09f4d-c2b1-41c4-8327-a4b668a727a3 > @nuxt/devtools@1.0.0-beta.1" has unmet peer dependency "vite@*".
warning "@nuxt/devtools > @nuxt/devtools-kit@1.0.0-beta.1" has unmet peer dependency "vite@*".
warning "@nuxt/devtools > vite-plugin-inspect@0.7.40" has unmet peer dependency "vite@^3.1.0 || ^4.0.0".
warning "@nuxt/devtools > vite-plugin-vue-inspector@4.0.0" has unmet peer dependency "vite@^3.0.0-0 || ^4.0.0-0".
[4/4] Building fresh packages...
$ nuxt prepare

 ERROR  Cannot find any nuxt version from /home/windymelt/src/github.com/windymelt/2024.scalamatsuri.org

  at loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2577:11)
  at async Object.run (node_modules/nuxi/dist/chunks/prepare.mjs:58:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1647:7)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1638:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1770:7) 



 ERROR  Cannot find any nuxt version from /home/windymelt/src/github.com/windymelt/2024.scalamatsuri.org

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

nuxtみつからないよエラー?が出てしまいました。
なにか追加の依存性などありますでしょうか。

nodeは`mise`(ASDF互換ツール)でインストールしています。

**Comment by windymelt** [comment]
自己解決しました。どういうわけか`/`に`package.json/`と`package-lock.json/`という**ディレクトリ**が生えていました。削除したところ治りました。
